In [1]:
import tensorflow as tf
tf.__version__

'1.13.1'

In [2]:
sess=tf.InteractiveSession()
x=tf.constant([[2,5,3,-5],
              [0,3,-2,5],
              [4,3,5,3],
              [6,1,4,0]])
y=tf.constant([[4,-7,4,-3,4],
              [6,4,-7,4,7],
              [2,3,2,1,4],
              [1,5,5,5,2]])
floatx=tf.constant([[2.,5.,3.,-5.],
              [0.,3.,-2.,5.],
              [4.,3.,5.,3.],
              [6.,1.,4.,0.]])

In [5]:
# sudah jelas untuk transpose
tf.transpose(x).eval()

array([[ 2,  0,  4,  6],
       [ 5,  3,  3,  1],
       [ 3, -2,  5,  4],
       [-5,  5,  3,  0]])

In [8]:
# inget perkalian matrik bisa dilakukan jika kolom dan baris sama 4x(4--> 4)x5
tf.matmul(x,y).eval()

array([[ 39, -10, -46,  -8,  45],
       [ 19,  31,   0,  35,  23],
       [ 47,  14,  20,  20,  63],
       [ 38, -26,  25, -10,  47]])

In [9]:
# matrik determinan, coba diingat ingat dulu, yang penghitungannya silang antara baris dan kolom
# http://belajar-online007.blogspot.com/2016/07/fungsi-determinan-matriks-dan-sifat.html
tf.matrix_determinant(floatx).eval()

817.9997

In [13]:
# matriks invers, ngitungnya pake determinan
# https://aimprof08.wordpress.com/2012/09/26/invers-matriks/
tf.matrix_inverse(floatx).eval()

array([[-0.00855745,  0.10513447, -0.18948655,  0.29584354],
       [ 0.12958434,  0.12224938,  0.01222495, -0.05134475],
       [-0.01955992, -0.18826404,  0.2811736 , -0.1809291 ],
       [-0.08557458,  0.05134474,  0.10513448, -0.0415648 ]],
      dtype=float32)

In [19]:
tf.matrix_solve(floatx,[[1],[1],[1],[1]]).eval()

array([[ 0.202934  ],
       [ 0.21271393],
       [-0.10757945],
       [ 0.02933985]], dtype=float32)

In [16]:
help(tf.matrix_solve)

Help on function matrix_solve in module tensorflow.python.ops.gen_linalg_ops:

matrix_solve(matrix, rhs, adjoint=False, name=None)
    Solves systems of linear equations.
    
    `Matrix` is a tensor of shape `[..., M, M]` whose inner-most 2 dimensions
    form square matrices. `Rhs` is a tensor of shape `[..., M, K]`. The `output` is
    a tensor shape `[..., M, K]`.  If `adjoint` is `False` then each output matrix
    satisfies `matrix[..., :, :] * output[..., :, :] = rhs[..., :, :]`.
    If `adjoint` is `True` then each output matrix satisfies
    `adjoint(matrix[..., :, :]) * output[..., :, :] = rhs[..., :, :]`.
    
    Args:
      matrix: A `Tensor`. Must be one of the following types: `float64`, `float32`, `complex64`, `complex128`.
        Shape is `[..., M, M]`.
      rhs: A `Tensor`. Must have the same type as `matrix`.
        Shape is `[..., M, K]`.
      adjoint: An optional `bool`. Defaults to `False`.
        Boolean indicating whether to solve with `matrix` or its (blo

In [20]:
# sekarang kita masuk dalam reduksi matriks
x=tf.constant([[1,2,3],
              [3,2,1],
              [-1,-2,-3]])
boolean_tensor=tf.constant([[True,False,True],
                           [False,False,True],
                           [True,False,False]])


In [23]:
# per baris matriks dikalikan
tf.reduce_prod(x,reduction_indices=1).eval()

array([ 6,  6, -6])

In [24]:
# cari nilai terkecil di setiap baris
tf.reduce_min(x,reduction_indices=1).eval()

array([ 1,  1, -3])

In [25]:
# cari nilai paling besar tiap baris
tf.reduce_max(x,reduction_indices=1).eval()

array([ 3,  3, -1])

In [26]:
#cari nilai rata-rata tiap baris
tf.reduce_mean(x,reduction_indices=1).eval()

array([ 2,  2, -2])

In [36]:
# help(tf.reduce_all)
tf.reduce_all(boolean_tensor,reduction_indices=1).eval()

array([False, False, False])

In [37]:
tf.reduce_any(boolean_tensor,reduction_indices=1).eval()

array([ True,  True,  True])

In [40]:
# sekarang kita masuk ke segmentasi
seg_ids=tf.constant([0,1,1,2,2])
tens1=tf.constant([[2,3,3,-5],
                  [0,3,-2,5],
                  [4,3,5,3],
                  [6,1,4,0],
                  [6,1,4,0]])
# segmen adalah indeksnya, 


In [41]:
# ini untuk menjumlahkan bagi baris yang segmennya sama
tf.segment_sum(tens1,seg_ids).eval()

array([[ 2,  3,  3, -5],
       [ 4,  6,  3,  8],
       [12,  2,  8,  0]])

In [42]:
# kalau ini untuk mengalikan jumlah baris yang mempunyai segmen yang sama
tf.segment_prod(tens1,seg_ids).eval()

array([[  2,   3,   3,  -5],
       [  0,   9, -10,  15],
       [ 36,   1,  16,   0]])

In [43]:
# mencari nilai maksimal setiap segmen
tf.segment_max(tens1,seg_ids).eval()

array([[ 2,  3,  3, -5],
       [ 4,  3,  5,  5],
       [ 6,  1,  4,  0]])

In [44]:
# mencari nilai minimal tiap segmen
tf.segment_min(tens1,seg_ids).eval()

array([[ 2,  3,  3, -5],
       [ 0,  3, -2,  3],
       [ 6,  1,  4,  0]])

In [45]:
tf.segment_mean(tens1,seg_ids).eval()

array([[ 2,  3,  3, -5],
       [ 2,  3,  1,  4],
       [ 6,  1,  4,  0]])

In [48]:
# berpindah ke sequences
x=tf.constant([[2,5,3,-5],
              [0,3,-2,5],
              [4,3,5,3],
              [6,1,4,0]])
listx=tf.constant([1,2,3,4,5,6,7,8])
listy=tf.constant([4,5,8,9])
boolx=tf.constant([[True,False],[False,True]])


In [49]:
# menemukan index/posisi nilai terkecil dari setiap baris di array x
tf.argmin(x,1).eval()

array([3, 2, 1, 3], dtype=int64)

In [50]:
# menemukan index/posisi nilai terbesar dari setiap baris di array x
tf.argmax(x,1).eval()

array([1, 3, 2, 0], dtype=int64)

In [53]:
# menemukan nilai dari array yang berbeda dari 2 array
tf.setdiff1d(listx,listy)[0].eval()

Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.sets.difference().


array([1, 2, 3, 6, 7])

In [54]:
tf.where(boolx).eval()

array([[0, 0],
       [1, 1]], dtype=int64)

In [55]:
tf.unique(listx)[0].eval()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
# sekarang berpindah ke tensorshaping
x=tf.constant([[2,5,3,-5],
              [0,3,-2,5],
              [4,3,5,3],
              [6,1,4,0]])


In [57]:
tf.shape(x).eval()

array([4, 4])

In [58]:
tf.size(x).eval()

16

In [60]:
tf.rank(x).eval()
help(tf.rank)

Help on function rank in module tensorflow.python.ops.array_ops:

rank(input, name=None)
    Returns the rank of a tensor.
    
    Returns a 0-D `int32` `Tensor` representing the rank of `input`.
    
    For example:
    
    ```python
    # shape of tensor 't' is [2, 2, 3]
    t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
    tf.rank(t)  # 3
    ```
    
    **Note**: The rank of a tensor is not the same as the rank of a matrix. The
    rank of a tensor is the number of indices required to uniquely select each
    element of the tensor. Rank is also known as "order", "degree", or "ndims."
    
    Args:
      input: A `Tensor` or `SparseTensor`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor` of type `int32`.
    
    @compatibility(numpy)
    Equivalent to np.ndim
    @end_compatibility



In [61]:
tf.reshape(x,[16,1]).eval()

array([[ 2],
       [ 5],
       [ 3],
       [-5],
       [ 0],
       [ 3],
       [-2],
       [ 5],
       [ 4],
       [ 3],
       [ 5],
       [ 3],
       [ 6],
       [ 1],
       [ 4],
       [ 0]])

In [64]:
help(tf.squeeze)
tf.squeeze(x).eval()

Help on function squeeze in module tensorflow.python.ops.array_ops:

squeeze(input, axis=None, name=None, squeeze_dims=None)
    Removes dimensions of size 1 from the shape of a tensor. (deprecated arguments)
    
    Instructions for updating:
    Use the `axis` argument instead
    
    Given a tensor `input`, this operation returns a tensor of the same type with
    all dimensions of size 1 removed. If you don't want to remove all size 1
    dimensions, you can remove specific size 1 dimensions by specifying
    `axis`.
    
    For example:
    
    ```python
    # 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
    tf.shape(tf.squeeze(t))  # [2, 3]
    ```
    
    Or, to remove specific size 1 dimensions:
    
    ```python
    # 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
    tf.shape(tf.squeeze(t, [2, 4]))  # [1, 2, 3, 1]
    ```
    
    Args:
      input: A `Tensor`. The `input` to squeeze.
      axis: An optional list of `ints`. Defaults to `[]`.
        If specified, only squee

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  5],
       [ 4,  3,  5,  3],
       [ 6,  1,  4,  0]])

In [67]:
tf.expand_dims(x,1).eval()

array([[[ 2,  5,  3, -5]],

       [[ 0,  3, -2,  5]],

       [[ 4,  3,  5,  3]],

       [[ 6,  1,  4,  0]]])

In [69]:
# sekarang berpindah ke tensor slicing and joining
t_matrix=tf.constant([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
t_array=tf.constant([1,2,3,4,9,8,6,5])
t_array2=tf.constant([2,3,4,5,6,7,8,9])


In [79]:
# parameternya adalah 2 diawal itu titik mulainya, dan 2,2 akhir itu adalah ukurannya
tf.slice(t_matrix,[0,1],[2,2]).eval()

array([[2, 3],
       [5, 6]])

In [88]:
# split atau pemisahan array
help(tf.split)
tf.split(t_array,2,0)

Help on function split in module tensorflow.python.ops.array_ops:

split(value, num_or_size_splits, axis=0, num=None, name='split')
    Splits a tensor into sub tensors.
    
    If `num_or_size_splits` is an integer type, then `value` is split
    along dimension `axis` into `num_split` smaller tensors.
    Requires that `num_split` evenly divides `value.shape[axis]`.
    
    If `num_or_size_splits` is not an integer type, it is presumed to be a Tensor
    `size_splits`, then splits `value` into `len(size_splits)` pieces. The shape
    of the `i`-th piece has the same size as the `value` except along dimension
    `axis` where the size is `size_splits[i]`.
    
    For example:
    
    ```python
    # 'value' is a tensor with shape [5, 30]
    # Split 'value' into 3 tensors with sizes [4, 15, 11] along dimension 1
    split0, split1, split2 = tf.split(value, [4, 15, 11], 1)
    tf.shape(split0)  # [5, 4]
    tf.shape(split1)  # [5, 15]
    tf.shape(split2)  # [5, 11]
    # Split 'va

[<tf.Tensor 'split_8:0' shape=(4,) dtype=int32>,
 <tf.Tensor 'split_8:1' shape=(4,) dtype=int32>]

In [89]:
# tiling alias memperbanyak
tf.tile([1,2],[3]).eval()

array([1, 2, 1, 2, 1, 2])

In [90]:
# padding, diberi jarak 0
tf.pad(t_matrix,[[0,1],[2,1]]).eval()

array([[0, 0, 1, 2, 3, 0],
       [0, 0, 4, 5, 6, 0],
       [0, 0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0, 0]])

In [98]:
# sudah jelas untuk penggabungan
tf.concat([t_array,t_array2],0).eval()

array([1, 2, 3, 4, 9, 8, 6, 5, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
# ini untuk menumpuk
tf.stack([t_array,t_array2]).eval()

array([[1, 2, 3, 4, 9, 8, 6, 5],
       [2, 3, 4, 5, 6, 7, 8, 9]])

In [102]:
# untuk mengembalikan per baris
tf.unstack([t_matrix])

[<tf.Tensor 'unstack:0' shape=(3, 3) dtype=int32>]

In [106]:
# untuk reverse matrik, dengan argumen mau horizontal atau cuma vertikal atau keduanya
tf.reverse(t_matrix,[True,False]).eval()

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])